version: "1.0"
services:
  db:
    container_name: db
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_DB: "fastapidb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - backend-fastapi-network
    volumes:
      - fastapi-postgres:/var/lib/postgresql
    ports:
      - "5432:5432"

  backend-fastapi: &fastapi
    container_name: backend-fasapi
    image: myimage
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    # volumes:
    #   - ./django-app:/src/code
    # command: /start
    networks:
      # - nginx-proxy
      - backend-fastapi-network

volumes:
  fastapi-postgres:
    external: true

networks:
  backend-fastapi-network:
