from collections import defaultdict
from datetime import datetime, timedelta
from random import randint
from typing import Annotated
from zoneinfo import ZoneInfo

import typer
from sqlalchemy import create_engine, delete, insert, select, update
from sqlalchemy.orm import Session

from app.core.config import settings
from app.db.models import (
    Driver,
    DriverVehicle,
    Vehicle,
    VehicleModel,
    VehicleTrackPoint,
)
from manage.generate_routes_points import generate_route

engine = create_engine(settings.DATABASE_URL)

app = typer.Typer()


@app.command()
def clear_db():
    """
    Clears database from autogenerated entites.
    """
    with Session(engine) as session:
        session.execute(delete(Vehicle).where(Vehicle.description == "Auto-generated"))
        session.execute(delete(Driver).where(Driver.first_name.startswith("auto generated")))
        session.commit()


@app.command()
def create_vehicle(
    enterprise_id: Annotated[
        list[int],
        typer.Option(
            help=(
                "Input enterprise id. For list of ids input a sequence of expression like "
                "'--enterprise-id 1 --enterprise-id 2 --enterprise-id 3."
            ),
        ),
    ],
    vehicle_num: Annotated[int, typer.Option(help=("Define how many vehicles should be generated."))] = 0,
):
    """
    Creates autogenerated Vehile, Driver and DriverVehicle entites.
    """
    enterprise_id = list(set(enterprise_id))
    with Session(engine) as session:
        models = session.execute(select(VehicleModel)).scalars().all()
        model_ids = [model.id for model in models]

        bulk_vehicle_list = []
        bulk_drivers_list = []
        enterprise_vehicle_dict = defaultdict(int)
        for i in range(vehicle_num):
            actual_enterprise_id = enterprise_id[randint(0, len(enterprise_id) - 1)]
            vehicle_data = {
                "description": "Auto-generated",
                "cost": randint(1000, 9999999),
                "manufactured_year": randint(2000, 2024),
                "mileage": randint(0, 500000),
                "brandmodel_id": model_ids[randint(0, len(model_ids) - 1)],
                "enterprise_id": actual_enterprise_id,
            }
            bulk_vehicle_list.append(vehicle_data)
            enterprise_vehicle_dict[actual_enterprise_id] += 1

            driver_data = {
                "first_name": f"auto generated {actual_enterprise_id} {i}",
                "last_name": f"auto generated {actual_enterprise_id} {i}",
                "salary": randint(10000, 300000),
            }
            bulk_drivers_list.append(driver_data)

        stmt = insert(Vehicle).values(bulk_vehicle_list).returning(Vehicle)

        result = session.execute(stmt)
        session.commit()
        created_vehicles = result.scalars().all()

        stmt = insert(Driver).values(bulk_drivers_list).returning(Driver)

        result = session.execute(stmt)
        session.commit()
        created_drivers = result.scalars().all()

        vehicle_driver_bulk_list = []
        driver_bulk_update_list = []
        for ind, driver_vehicle in enumerate(zip(created_drivers, created_vehicles)):
            driver, vehicle = driver_vehicle
            vehicle_driver_data = {
                "is_active_driver": (ind + 1) % 10 == 1,
                "driver_id": driver.id,
                "vehicle_id": vehicle.id,
            }
            vehicle_driver_bulk_list.append(vehicle_driver_data)

            driver_data = {
                "id": driver.id,
                "enterprise_id": vehicle.enterprise_id,
            }
            driver_bulk_update_list.append(driver_data)

        stmt = update(Driver)
        result = session.execute(stmt, driver_bulk_update_list)
        session.commit()

        stmt = insert(DriverVehicle).values(vehicle_driver_bulk_list).returning(DriverVehicle)
        result = session.execute(stmt)
        session.commit()


@app.command()
def generate_track_points(
    vehicle_id: Annotated[int, typer.Option(help=("Vehicle ID, track ponts should be generated for."))],
    radius: Annotated[int, typer.Option(help=("Track pont radius."))] = None,
):
    coords = ([13.384116, 52.533558], [13.428726, 52.519355])
    points_dict = generate_route(*coords, radius)

    with Session(engine) as session:
        bulk_points_list = []
        time_now = datetime.now(tz=ZoneInfo("UTC"))
        for time_offset, point in points_dict.items():
            data = {
                "date_time": time_now + timedelta(seconds=(10 * time_offset)),
                "geotag": f"POINT({point.longitude} {point.latitude})",
                "vehicle_id": vehicle_id,
            }
            bulk_points_list.append(data)
        stmt = insert(VehicleTrackPoint).values(bulk_points_list).returning(VehicleTrackPoint)
        result = session.execute(stmt)
        session.commit()
        result.scalars().all()


if __name__ == "__main__":
    app()
