"""initial

Revision ID: 431c1e3af4af
Revises: 
Create Date: 2024-01-23 10:08:10.066430

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "431c1e3af4af"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cost", sa.BigInteger(), nullable=True),
        sa.Column("manufactured_year", sa.Integer(), nullable=False),
        sa.Column("mileage", sa.BigInteger(), nullable=False),
        sa.Column("is_in_work", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicle_id"), "vehicle", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vehicle_id"), table_name="vehicle")
    op.drop_table("vehicle")
    # ### end Alembic commands ###
