"""Enterprise typo

Revision ID: 6e6c390d35d3
Revises: f662070d1e68
Create Date: 2024-02-07 13:32:43.141289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e6c390d35d3"
down_revision: Union[str, None] = "f662070d1e68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("driver", sa.Column("enterprise_id", sa.BigInteger(), nullable=True))
    op.drop_constraint("driver_enterpise_id_fkey", "driver", type_="foreignkey")
    op.create_foreign_key(None, "driver", "enterprise", ["enterprise_id"], ["id"], ondelete="SET NULL")
    op.drop_column("driver", "enterpise_id")
    op.add_column("vehicle", sa.Column("enterprise_id", sa.BigInteger(), nullable=True))
    op.drop_constraint("vehicle_enterpise_id_fkey", "vehicle", type_="foreignkey")
    op.create_foreign_key(None, "vehicle", "enterprise", ["enterprise_id"], ["id"], ondelete="SET NULL")
    op.drop_column("vehicle", "enterpise_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vehicle", sa.Column("enterpise_id", sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "vehicle", type_="foreignkey")
    op.create_foreign_key(
        "vehicle_enterpise_id_fkey", "vehicle", "enterprise", ["enterpise_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("vehicle", "enterprise_id")
    op.add_column("driver", sa.Column("enterpise_id", sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "driver", type_="foreignkey")
    op.create_foreign_key(
        "driver_enterpise_id_fkey", "driver", "enterprise", ["enterpise_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("driver", "enterprise_id")
    # ### end Alembic commands ###
