"""Migration message

Revision ID: 70de8139a2ee
Revises: 384f7cd64219
Create Date: 2024-05-14 19:52:41.120199

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70de8139a2ee"
down_revision: Union[str, None] = "384f7cd64219"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vehicle", sa.Column("purchase_datetime", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle", "purchase_datetime")
    # ### end Alembic commands ###
