"""add M2M table for drivera and vehicles

Revision ID: 71335498f67a
Revises: 36fa4e1b6b71
Create Date: 2024-02-01 21:55:40.530779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71335498f67a"
down_revision: Union[str, None] = "36fa4e1b6b71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vehicle_id", table_name="vehicle")
    op.create_index(op.f("ix_vehicle_id"), "vehicle", ["id"], unique=True)
    op.create_table(
        "drivervehicle",
        sa.Column("is_active_driver", sa.Boolean(), nullable=False),
        sa.Column("driver_id", sa.BigInteger(), nullable=False),
        sa.Column("vehicle_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["driver.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("driver_id", "vehicle_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drivervehicle")
    op.drop_index(op.f("ix_vehicle_id"), table_name="vehicle")
    op.create_index("ix_vehicle_id", "vehicle", ["id"], unique=False)
    # ### end Alembic commands ###
