"""create models and brands

Revision ID: a0cd23135c33
Revises: 431c1e3af4af
Create Date: 2024-01-25 22:26:47.157591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0cd23135c33"
down_revision: Union[str, None] = "431c1e3af4af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehiclebrand",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("brand_name", sa.String(), nullable=False),
        sa.Column("original_country", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehiclebrand_id"), "vehiclebrand", ["id"], unique=False)
    op.create_table(
        "vehiclemodel",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("vehicle_type", sa.String(), nullable=False),
        sa.Column("passenger_capacity", sa.Integer(), nullable=False),
        sa.Column("tonnage", sa.Integer(), nullable=False),
        sa.Column("fuel_capacity", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["vehiclebrand.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehiclemodel_id"), "vehiclemodel", ["id"], unique=False)
    op.add_column("vehicle", sa.Column("model_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, "vehicle", "vehiclemodel", ["model_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vehicle", type_="foreignkey")
    op.drop_column("vehicle", "model_id")
    op.drop_index(op.f("ix_vehiclemodel_id"), table_name="vehiclemodel")
    op.drop_table("vehiclemodel")
    op.drop_index(op.f("ix_vehiclebrand_id"), table_name="vehiclebrand")
    op.drop_table("vehiclebrand")
    # ### end Alembic commands ###
