"""add nullable in Vehicle model

Revision ID: be705f3c420d
Revises: 87ca0d491c8e
Create Date: 2024-01-29 20:13:35.834199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be705f3c420d"
down_revision: Union[str, None] = "87ca0d491c8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("vehicle", "brandmodel_id", existing_type=sa.BIGINT(), nullable=True)
    op.drop_constraint("vehicle_brandmodel_id_fkey", "vehicle", type_="foreignkey")
    op.create_foreign_key(None, "vehicle", "vehiclemodel", ["brandmodel_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vehicle", type_="foreignkey")
    op.create_foreign_key("vehicle_brandmodel_id_fkey", "vehicle", "vehiclemodel", ["brandmodel_id"], ["id"])
    op.alter_column("vehicle", "brandmodel_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
