"""fix model field name

Revision ID: deeda98edac0
Revises: a0cd23135c33
Create Date: 2024-01-25 22:38:16.559126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "deeda98edac0"
down_revision: Union[str, None] = "a0cd23135c33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vehicle", sa.Column("brandmodel_id", sa.BigInteger(), nullable=False))
    op.drop_constraint("vehicle_model_id_fkey", "vehicle", type_="foreignkey")
    op.create_foreign_key(None, "vehicle", "vehiclemodel", ["brandmodel_id"], ["id"])
    op.drop_column("vehicle", "model_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vehicle", sa.Column("model_id", sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "vehicle", type_="foreignkey")
    op.create_foreign_key("vehicle_model_id_fkey", "vehicle", "vehiclemodel", ["model_id"], ["id"])
    op.drop_column("vehicle", "brandmodel_id")
    # ### end Alembic commands ###
