"""Add cascade delete in user_enterprise_associacion_table

Revision ID: f39ce544b8b3
Revises: 6e6c390d35d3
Create Date: 2024-02-12 11:38:17.331465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f39ce544b8b3"
down_revision: Union[str, None] = "6e6c390d35d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_enterprise_association_table_user_id_fkey", "user_enterprise_association_table", type_="foreignkey"
    )
    op.drop_constraint(
        "user_enterprise_association_table_enterprise_id_fkey", "user_enterprise_association_table", type_="foreignkey"
    )
    op.create_foreign_key(None, "user_enterprise_association_table", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        None, "user_enterprise_association_table", "enterprise", ["enterprise_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_enterprise_association_table", type_="foreignkey")
    op.drop_constraint(None, "user_enterprise_association_table", type_="foreignkey")
    op.create_foreign_key(
        "user_enterprise_association_table_enterprise_id_fkey",
        "user_enterprise_association_table",
        "enterprise",
        ["enterprise_id"],
        ["id"],
    )
    op.create_foreign_key(
        "user_enterprise_association_table_user_id_fkey",
        "user_enterprise_association_table",
        "user",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
